### PR TITLE
Fix few typos, stale README.md and include clean up code when needed

### LINKED ISSUE #421: I'm having trouble with finding reference for this "VirtualNodeName" under ColorTellerService.
I'm having trouble with finding reference for this "VirtualNodeName" under ColorTellerService. Should "VirtualServiceName" be set to the name of the virtual service, like "ColorTellerService.VirtualServiceName", instead? Or the VirtualNodeName will return something different but hasn't been documented in the "Return values" section of https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appmesh-virtualservice.html

https://github.com/aws/aws-app-mesh-examples/blob/5a2d04227593d292d52e5e2ca638d808ebed5e70/walkthroughs/howto-servicediscovery-cloudmap/mesh.yaml#L95

### PR DESCRIPTION
**Pull request by suniltheta**
Fix few typos, stale README.md and include clean up code when needed

Also fix #421

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: examples/apps/colorapp/src/colorteller/deploy.sh [hunk 1]
```diff
@@ -27,9 +27,17 @@ ecr_login() {
     fi
 }
 
+describe_create_ecr_registry() {
```
Comment (suniltheta) [inline examples/apps/colorapp/src/colorteller/deploy.sh:30]: This will create the registry if it doesn't exist already. Otherwise we would try to upload the file and just fail instead.

File: walkthroughs/howto-servicediscovery-cloudmap/README.md [hunk 2]
```diff
@@ -15,13 +15,16 @@ Set or export the following environment variables with appropriate values for yo
 
 ```bash
 # Your AWS account ID
-export AWS_ACCOUNT_ID=999999999999
+export AWS_ACCOUNT_ID=<YOUR AWS ACCOUNT ID>
```
Comment (suniltheta) [inline walkthroughs/howto-servicediscovery-cloudmap/README.md:18]: git didn't let me commit without this change. It thought this was a secret that I am committing. I could have done `git commit --no-verify`. But anyway.

File: walkthroughs/howto-servicediscovery-cloudmap/mesh.yaml [hunk 3]
```diff
@@ -92,7 +92,7 @@ Resources:
           Action:
             Target:
               VirtualService:
-                VirtualServiceName: !GetAtt ColorTellerService.VirtualNodeName
+                VirtualServiceName: !GetAtt ColorTellerService.VirtualServiceName
```
Comment (suniltheta) [inline walkthroughs/howto-servicediscovery-cloudmap/mesh.yaml:95]: This particularly address the #421 issue here.

**Review by karanvasnani — APPROVED** [review]
